# Training configuration
GPU: [0,1,2,3]

VERBOSE: False

SWINUNET:
  IMG_SIZE: 128
  PATCH_SIZE: 1
  IN_CHANS: 1
  OUT_CHANS: 1
  WIN_SIZE: 8
  EMB_DIM: 48
  DEPTH_EN: [2, 6, 8, 16]
  HEAD_NUM: [8, 8, 8, 8]
  MLP_RATIO: 4.0
  QKV_BIAS: True
  QK_SCALE: 8
  DROP_RATE: 0.
  ATTN_DROP_RATE: 0.
  DROP_PATH_RATE: 0.1
  APE: False
  PATCH_NORM: True
  USE_CHECKPOINTS: False
  FINAL_UPSAMPLE: 'bilinear'

MODEL:
  MODE: 'Denoising'

# Optimization arguments.
OPTIM:
  BATCH: 16
  EPOCHS: 500
  # EPOCH_DECAY: [10]
  LR_INITIAL: 1e-3 #2e-4
  LR_MIN: 1e-5 #1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: True
  TRAIN_PS: 128
  VAL_PS: 128 
  # TRAIN_DIR: './datasets/Denoising_DIV2K/train'       # path to training data
  # VAL_DIR: './datasets/Denoising_DIV2K/test' # path to validation data
  SAVE_DIR: '/home/users/a/akhaury/scratch/SingleChannel_Deconv/Trained_Models/SUNet'           # path to save models and images
